services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_VOLUME}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - caddy
    restart: unless-stopped
    labels:
      - homepage.group=Various
      - homepage.name=Home Assistant
      - homepage.description=Home Automation
      - homepage.icon=si-homeassistant
      - homepage.href=https://hass.${PUB_DOMAIN}

  mqtt:
    image: "eclipse-mosquitto:openssl"
    container_name: "mosquitto"
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_VOLUME}/homeassistant/mqtt/config:/mosquitto/config
      - ${BASE_VOLUME}/homeassistant/mqtt/data:/mosquitto/data
      - ${BASE_VOLUME}/homeassistant/mqtt/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - caddy
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=MQTT
      - homepage.description=Mosquitto Message Broker
      - homepage.icon=si-mqtt

  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt
    depends_on:
      - mqtt
    environment:
      - TZ=${TZ}
    devices:
      - /dev/bus/usb
    volumes:
      - ${BASE_VOLUME}/homeassistant/rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - ${BASE_VOLUME}/homeassistant/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt
    networks:
      - caddy
    restart: unless-stopped
    labels:
      - homepage.group=Various
      - homepage.name=LoRa Meter Reader
      - homepage.description=RTL-SDR AMR to MQTT message broker

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    depends_on:
      - mqtt
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_VOLUME}/homeassistant/zigbee2mqtt/data:/app/data
    networks:
      - caddy
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Zigbee 2 MQTT
      - homepage.description=Zigbee to MQTT translator
      - homepage.icon=si-zigbee2mqtt
      - homepage.href=zigbee2mqtt.${INT_DOMAIN}

networks:
  caddy:
    name: caddy-net
    external: true
