services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_VOLUME}/homepage/config:/app/config
    networks:
      - caddy-net
      - socketproxy-net
    restart: unless-stopped
  dockersocketproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockersocketproxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socketproxy-net
    restart: unless-stopped
    # labels:
    #   - homepage.group=Various
    #   - homepage.name=Homepage
    #   - homepage.description=Status Pages
    #   - homepage.icon=si-homepage

networks:
  caddy-net:
    name: caddy-net
    external: true
  socketproxy-net:
    name: socketproxy-net
