version: "3.9"
services:
  siyuan:
    image: b3log/siyuan
    command: [ '--workspace=/siyuan/workspace/', '--accessAuthCode=${AuthCode}' ]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - caddy-net
    volumes:
      - ${BASE_VOLUME}/siyuan/workspace:/siyuan/workspace
    restart: unless-stopped

networks:
  caddy-net:
    name: caddy-net
    external: true
