services:
  caddy:
    # image: caddy
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:builder AS builder
        RUN caddy-builder github.com/caddy-dns/route53
        FROM caddy:latest
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    container_name: caddy
    restart: always
    environment:
      - TZ=${TZ}
    env_file:
      - caddy.env
    volumes:
      - ${BASE_VOLUME}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${BASE_VOLUME}/caddy/config:/config
      - ${BASE_VOLUME}/caddy/data:/data
      - ${BASE_VOLUME}/caddy/test:/wdata3
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 784:784 # DNS-over-QUIC
      - "853:853/tcp" # DNS-over-TLS
      - "853:853/udp" # DNS-over-QUIC
    networks:
      - caddy-net
    labels:
      - homepage.group=Network
      - homepage.name=Caddy
      - homepage.description=Reverse Proxy
      - homepage.icon=si-caddy

networks:
  caddy-net:
    name: caddy-net
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
