services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - TZ=America/Phoenix
      - PUID=1000
      - PGID=1000
    volumes:
      - ${BASE_VOLUME}/:/var/syncthing/volumes
    networks:
      - caddy
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - homepage.group=Data
      - homepage.name=Syncthing
      - homepage.description=File syncing
      - homepage.icon=si-syncthing
      - homepage.href=https://syncthing.${BASE_DOMAIN}

networks:
  caddy:
    name: caddy-net
    external: true
